name: Build binaries

on:
  push:
    paths: ["*.au3"]

jobs:
  build-binaries:
    runs-on: windows-latest
    env:
      LANGUAGE_CHANGER: language-changer
      DLC_TOGGLER: dlc-toggler
      DLC_UNINSTALLER: dlc-uninstaller
      CHANGED: changed_files.txt
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Install AutoIt3'
        run: choco install autoit.portable --version 3.3.14.5 -y
      - name: 'Get changed files'
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > ${{ env.CHANGED }}
      - name: 'Build ${{ env.LANGUAGE_CHANGER }}'
        continue-on-error: true
        run: >-
          findstr /L /B "${{ env.LANGUAGE_CHANGER }}.au3" ${{ env.CHANGED }} >NUL
          && del "${{ env.LANGUAGE_CHANGER }}*.exe"
          && ./_compile.bat "${{ env.LANGUAGE_CHANGER }}.au3"
          || echo "${{ env.LANGUAGE_CHANGER }} not modified"
      - name: 'Build ${{ env.DLC_TOGGLER }}'
        continue-on-error: true
        run: >-
          findstr /L /B "${{ env.DLC_TOGGLER }}.au3" ${{ env.CHANGED }} >NUL
          && del "${{ env.DLC_TOGGLER }}*.exe"
          && ./_compile.bat "${{ env.DLC_TOGGLER }}.au3"
          || echo "${{ env.DLC_TOGGLER }} not modified"
      - name: 'Build ${{ env.DLC_UNINSTALLER }}'
        continue-on-error: true
        run: >-
          findstr /L /B "${{ env.DLC_UNINSTALLER }}.au3" ${{ env.CHANGED }} >NUL
          && del "${{ env.DLC_UNINSTALLER }}*.exe"
          && ./_compile.bat "${{ env.DLC_UNINSTALLER }}.au3"
          || echo "${{ env.DLC_UNINSTALLER }} not modified"
      - name: 'Commit binaries'
        run: |
          git config --global user.name 'anadius'
          git config --global user.email '8550471+anadius@users.noreply.github.com'
          git add *.exe
          git commit -m "Update binaries"
          git push
